---
- name: Install and configure lighttpd web server
  hosts: all
  become: yes
  vars_prompt:
    - name: server_port
      prompt: Enter the server port number
      private: no

  tasks:
    - name: Install lighttpd
      apt:
        name: lighttpd
        state: latest
        update_cache: yes

    - name: Generate configuration file
      template:
        src: myconfig.j2
        dest: /etc/lighttpd/lighttpd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Start lighttpd service
      service:
        name: lighttpd
        state: started
