---
# Modified Playbook with vars_prompt 

- name: Install lighttpd web server
  become: yes
  apt:
    name: lighttpd
    state: latest
    update_cache: yes

- name: Prompt for server port
  vars_prompt:
    - name: server_port
      prompt: Enter the server port number
      private: no

- name: Generate configuration file
  template:
    src: myconfig.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: '0644'

- name: Start lighttpd service
  become: yes
  service:
    name: lighttpd
    state: started
